--Retrieve the total number of rentals made in the Sakila database. 
select count(*) from rental;

--Find the average rental duration (in days) of movies rented from the Sakila database.
select avg(datediff(return_date,rental_date)) as avg_rental_duration from rental where rental_id=1

--Display the first name and last name of customers in uppercase. 
select upper(first_name),upper(last_name) from customer

--Extract the month from the rental date and display it alongside the rental ID. 
select month(rental_date),rental_id from rental

--Retrieve the count of rentals for each customer (display customer ID and the count of rentals).
select customer_id,count(customer_id) as count_rentals from rental group by customer_id

--Find the total revenue generated by each store.
select store_id, sum(p.amount) from payment p 
inner join store s on s.manager_staff_id = p.staff_id
group by store_id ;

--Display the title of the movie, customers first name, and last name who rented it. 
select f.title, c.first_name,c.last_name from film f
inner join inventory I on I.film_id=f.film_id
inner join rental r on r.inventory_id=r.rental_id
inner join customer c on c.store_id=i.store_id

--Retrieve the names of all actors who have appeared in the film "Gone with the Wind."
 select a.first_name,a.last_name from film f
inner join actor a on a.actor_id=f.film_id
inner join film_actor fa on fa.film_id=f.film_id
where f.title='Gone with the Wind'
/* there is no film like 'Gone with the Wind' hence output as null*/

--Determine the total number of rentals for each category of movies. 
category, film, and rental
select c.name as category,count(rental_id) as total_rental from rental r
inner join inventory i on r.inventory_id=i.inventory_id
inner join film f on i.film_id=f.film_id
inner join film_category fc on i.film_id=fc.film_id
inner join category c on c.category_id=fc.category_id
group by category

--Find the average rental rate of movies in each language. 
select l.name as language,avg(rental_rate) as avg_rental_rate from language l
inner join film f on f.language_id=l.language_id
group by l.name

--Retrieve the customer names along with the total amount they've spent on rentals.
select concat(c.first_name," " ,c.last_name) as name, sum(p.amount) from customer c
join rental r on r.customer_id=c.customer_id
join payment p on c.customer_id=p.customer_id
group by name  

--List the titles of movies rented by each customer in a particular city (e.g., 'London'). 
select c.first_name,c.last_name,f.title as rented_movie from customer c
join address a on c.address_id=a.address_id
join rental r on c.customer_id=r.customer_id
join city ci on a.city_id=ci.city_id
join inventory i on r.inventory_id=i.inventory_id
join film f on f.film_id=i.film_id
where ci.city='London'
group by c.first_name,c.last_name,f.title

--Display the top 5 rented movies along with the number of times they've been rented. 
select f.title,count(*) as rental_count from film f
join inventory i on f.film_id=i.film_id
join rental r on i.inventory_id=r.inventory_id
group by f.title 
order by rental_count desc
limit 5

--Determine the customers who have rented movies from both stores (store ID 1 and store ID 2). 
select c.customer_id,c.first_name,c.last_name from customer c
join rental r on c.customer_id=r.customer_id
join inventory i on r.inventory_id=i.inventory_id
join store s on i.store_id=s.store_id
where s.store_id in (1,2)
group by c.customer_id,
c.first_name,c.last_name
having count(distinct s.store_id)=2